name: Build-And-Deploy

on:
  workflow_run:
    workflows: [ "Lint"]
    types:
      - completed
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prebuild - install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Prebuild - install dependencies
        run: npm install
      - name: Prebuild - generate grammar
        run: npm run generate-grammar-prod
      - name: Prebuild - build app
        run: npm run build
      - name: Prebuild - fetch datasets
        run: npm run fetch-datasets
      - name: Prebuild - cleanup
        run: rm -rf node_modules
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuzudb/explorer:latest
          build-args: |
            SKIP_GRAMMAR=true
            SKIP_BUILD_APP=true
            SKIP_DATASETS=true
