name: Lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linters without auto-fix (on master)
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        run: ./node_modules/.bin/eslint --ext .js,.vue src

      - name: Run linters with auto-fix (on non-master branches)
        if: github.event_name == 'push' && github.event.ref != 'refs/heads/master'
        run: ./node_modules/.bin/eslint --ext .js,.vue src --fix

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Lint Bot
          message: 'Run linters'